config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'about', to: 'pages#about'
  resources :articles
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def new
        @article = Article.new
    end
    def edit
        @article = Article.find(params[:id])
    end
    def index
        @articles = Article.all
      end
      def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash[:notice] = "Article was deleted"
        redirect_to articles_path
       end
    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
         flash[:notice] = "Article was updated"
         redirect_to article_path(@article)
        else
         flash[:notice] = "Article was not updated"
         render 'edit'
        end
    end
    def show
        @article = Article.find(params[:id])
    end
    def create
        @article = Article.new(article_params)
        if @article.save
         flash[:notice] = "Article was successfully created"
         redirect_to article_path(@article)
        else
         render 'new'
        end
       end
    private
    def article_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>
<%= form_for @article do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<p>
<%= link_to "Create new article", new_article_path %>
</p>
<table>
 <tr>
  <th>Title</th>
  <th>Description</th>
 </tr>
 <% @articles.each do |article| %>
 <tr>
  <td><%= article.title %></td>
  <td><%= article.description %></td>
  <td><%= link_to 'Edit', edit_article_path(article) %></td>
  <td><%= link_to 'Show', article_path(article) %></td>
  <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
 </tr>
 <% end %>
</table>
<%= link_to 'Back', articles_path %>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>
<%= form_for @article do |f| %>
    <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
   </p>
   <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
   </p>
   <p>
    <%= f.submit %>
   </p>
<% end %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<p>
 Title: <%= @article.title %>
</p>
<p>
 Description: <%= @article.description %>
</p>
<%= link_to "Edit", edit_article_path(@article) %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "components/menu"%>
    </head>

  <body>
  <% flash.each do |name, msg| %>
    <ul>
     <li><%= msg %></li>
    </ul>
<% end %>
    <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About Blog</h1>
<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>
<%= link_to 'About', about_path %>